### ISSUE TITLE
Access over HTTPS not available

### ISSUE THREAD

**Issue by achraf52** [VoIPDown/voipdown.github.io#1]
It would be beneficial to have HTTPS access for the website http://voipdown.com/ and the corresponding JavaScript source file "voipdown.min.js" so that HTTPS websites can still protest by including the widget without raising an "other non-secure sources" alert.

As you're using github.io to host the files, I'd recommend following this tutorial for a free solution:
https://blog.keanulee.com/2014/10/11/setting-up-ssl-on-github-pages.html

After you have setup CloudFlare and the SSL certificate has been issued, I'll make a pull request with the appropriate code changes to the code snippet.

**Comment by zakelfassi** [comment]
That one is on the task list - but I figured "how many HTTPS are in Morocco" and what % of them would wanna add it? :)
I'm doing it nonetheless!

**Comment by achraf52** [comment]
Here's one: https://www.achraf52.com/
So... Yeah, do it man, and add me to the supporters list.

**Comment by zakelfassi** [comment]
Added in 523e9877 + fixed HTTPS URIs in b6112d5. Need to wait for DNS updates.

**Comment by achraf52** [comment]
Triggered DNS update for OpenDNS. The website is now is SSL mode.
