### ISSUE TITLE
How To contribute to the projet ?

### ISSUE THREAD

**Issue by soub4i** [VoIPDown/voipdown.github.io#10]
Hi , Thanks for this git
i have a question
How i can help or contribute to this projet ?

**Comment by Mehdiway** [comment]
1. Fork the project on GitHub to your repository
2. Make any changes you want then commit
3. Make a pull request
4. Pray for the merge lord to consider your changes

**Comment by zakelfassi** [comment]
@AbderrahimSoubaiElidrissi here's an extensive guide > https://guides.github.com/activities/contributing-to-open-source/

@Mehdiway 4th hahahahahahaha
