### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by imadarchid** [VoIPDown/voipdown.github.io#11]
Hey, 

This isn't an issue related to the website, but I want to say that if we want to fight ISPs and the ANRT in their decisions, badges aren't enough if they're not displayed in high traffic websites. 

I suggest, if it's possible, an app that let's Moroccan users use a VPN more simply. They just need to download the app, click a button and voilà they're connected via VPN. 

The app may function in these ways : 
- We provide our own VPN servers using some users donations and ads. 
- Or we develop a bot that looks for VPN servers and make them available for the users. ( Like a web service that fetchs servers and then make them available for use by the app).

I've made an Android prototype based on a project hosted on Github, here are the screenshots : 
http://imgur.com/N5cBcHx
http://imgur.com/2OKpX97

Just a suggestion if anybody is interested.

**Comment by zakelfassi** [comment]
> badges aren't enough if they're not displayed in high traffic websites.

True. But, all moroccan high traffic websites are press sites; to paraphrase one of them "I don't want to be in the middle"; Read: "All we care about is the ad money." -- but to be honest, _why would a shortsighted industry give a s*_?

> an app that let's Moroccan users use a VPN more simply

Excellent idea - I've thought about this, but I also thought about the the cracking down that would happen  as soon as it hits the market! But that's not the main issue ...

> some users donations and ads.

**THIS** is the main issue.

If this VoIPDown experience taught me anything, it would be _how selfish people can be_. I'd never place a bet on donations. Or users' payments. (and even ads - just look at the current ~$0.03 CPM for Admob/MA and how many people you'd need to pay ONE decent server. I say a lot. Financially not viable.)

> a bot that looks for VPN servers

There's something interesting about this part. To be discussed more.

**Comment by imadarchid** [comment]
Okay so the second option is better. There's an open-source project called [VPNGate](http://www.vpngate.net/) that offers a list of VPNs (over 9000 VPNs updated every minute) with data about servers : 
- Country 
- IP Adress
- How many users connected (So we can choose the best)
- Supports L2TP/IPsec and OpenVPN protocols.

It offers also a [CSV list](http://www.vpngate.net/api/iphone/) that we could use to parse data from the website to the app. Maybe we could use it ?

**Comment by ankouc** [comment]
Or you embed an "on demand vpn" in a voip application!

2016-06-29 17:02 GMT-04:00 Imad Archid notifications@github.com:

**Comment by imadarchid** [comment]
"On Demand VPN" is only available in iOS devices I think.
I didin't understand how you could embed it in a VoIP app, I thought that it must be implemented by the developers of the VoIP app.

**Comment by ankouc** [comment]
You establish a tunnel for the time of the call. You will need less
ressources this way.

2016-06-29 17:49 GMT-04:00 Imad Archid notifications@github.com:

**Comment by imadarchid** [comment]
I see, but as I said, I think this need to be done by the app developer (Whatsapp, Viber...). We're looking for a way to let Moroccan users connect to these apps and bypass the ISPs block.
