### ISSUE TITLE
Wordpress Plugin

### ISSUE THREAD

**Issue by imadarchid** [VoIPDown/voipdown.github.io#5]
Hey,

Here's a little wordpress plugin to add the counter on WP sites easily : 

https://github.com/imadarchid/voipdownWordpress

I think it might help people not familiar with adding code manualy on their WP websites.

**Comment by zakelfassi** [comment]
That's awesome! I'll add it to the site.
Any way you could publish this on WP plugins repo to make it even simpler!?

**Comment by imadarchid** [comment]
Done ! It's pending review by Wordpress.org, I'll post the link here later if it gets approved.

**Comment by imadarchid** [comment]
Hey @zakelfassi the plugin is live on WP repo.
https://wordpress.org/plugins/badge-for-voipdown/

**Comment by zakelfassi** [comment]
@imadarchid updated the homepage with the new link. Also added you to the VoIPDown github organisation ([check this out](https://help.github.com/articles/transferring-a-repository/) if you wanna transfer the WP plugin here.)

**Comment by imadarchid** [comment]
Done!

**Comment by zakelfassi** [comment]
Awesomeness 🖖
